fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=775"]
    - id: check-merge-conflict
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        exclude: > # multiline regex pattern
          (?x)^(
            scratch/.*
          )
- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
    - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
    - id: flake8
      exclude: > # multiline regex pattern
        (?x)^(
          scratch/.*
        )
      additional_dependencies: [flake8-comprehensions]
      args: ["--config=setup.cfg"]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
        types: [text]  # overwrite types: [rst]
        types_or: [python, rst]
      - id: rst-inline-touching-normal
        types: [text]  # overwrite types: [rst]
        types_or: [python, rst]
-   repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.9.1
    hooks:
    - id: sphinx-lint
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        exclude: > # multiline regex pattern
          (?x)^(
            scratch/.*
          )
        types_or: [python, rst, markdown]
        additional_dependencies: [tomli]
        args: ["--toml=pyproject.toml"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
        exclude: (.txt|^docs/JOSS1|^docs/JOSS2|^examples/data/)
        stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
    -   id: trailing-whitespace
        stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
        exclude: (.txt|^docs/JOSS1|^docs/JOSS2|^examples/data/)
